fix(123): change domain of share
AlistGo/alist pull request #7354
Opened 2024-10-17 05:49 UTC by lpcheng1208

Repair: 123 pan share domain name modification

2024-10-20 05:34 UTC, xrgzs requested changes
Is it possible to provide an input box to modify the domain name, and can the non-shared 123 driver also be added?

2024-11-09 03:03 UTC, kaiserverkcraft commented
这个不是备用的吗 建议改成一个可选的吧 官方默认还是推荐123pan.com

2024-11-09 11:36 UTC, xrgzs commented
> 这个不是备用的吗 建议改成一个可选的吧 官方默认还是推荐123pan.com

最近发现123分享出来的两个链接都是123865🤪

![](https://github.com/user-attachments/assets/bef66930-e551-43eb-b611-88b6acb65d76)

2024-11-09 15:42 UTC, lpcheng1208 commented
> 这个不是备用的吗 建议改成一个可选的吧 官方默认还是推荐123pan.com
因为 123pan 前面主域名都被反诈骗了，现在把分享放到123865.com 底下了

2025-06-25 07:29 UTC, closed without merging